import Link from "next/link";
import Logo from "@/components/logo";

const productLinks = [{ label: "Home", href: "/" }, { label: "Create", href: "/workspace" }, { label: "Pricing", href: "/#pricing" }, { label: "Contact", href: "/contact" }];
const legalLinks = [{ label: "Privacy Policy", href: "/privacy" }, { label: "Terms of Service", href: "/terms" }];

export default function FooterSection() {
  return <footer className="relative isolate overflow-hidden border-t border-white/[.07] bg-[#0b0b0c] text-white"><div aria-hidden className="pointer-events-none absolute inset-x-0 bottom-8 z-0 whitespace-nowrap px-[3vw] font-serif text-[clamp(7rem,20vw,19rem)] leading-[.78] tracking-[-.09em] text-white/[.055]">LA MUSICA</div><div className="relative z-10 mx-auto grid max-w-[90rem] gap-12 px-5 py-16 sm:px-8 md:grid-cols-[1.4fr_1fr_1fr] lg:px-12"><div><Link href="/" aria-label="La Musica home"><Logo variant="horizontal" className="h-9 w-auto" /></Link><p className="mt-5 max-w-xs text-base leading-7 text-white/52">Your ideas deserve a soundtrack.</p></div><nav aria-label="Product"><h2 className="text-xs font-semibold uppercase tracking-[.14em] text-white/38">Product</h2><ul className="mt-5 space-y-3">{productLinks.map((link) => <li key={link.href}><Link href={link.href} className="text-sm text-white/60 transition hover:text-white">{link.label}</Link></li>)}</ul></nav><nav aria-label="Legal"><h2 className="text-xs font-semibold uppercase tracking-[.14em] text-white/38">Legal</h2><ul className="mt-5 space-y-3">{legalLinks.map((link) => <li key={link.href}><Link href={link.href} className="text-sm text-white/60 transition hover:text-white">{link.label}</Link></li>)}</ul></nav></div><div className="relative z-10 mx-auto flex max-w-[90rem] flex-col gap-3 border-t border-white/[.07] px-5 py-6 text-sm text-white/38 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-12"><p>© {new Date().getFullYear()} La Musica. All rights reserved.</p><p>Made for people with something to say.</p></div></footer>;
}
